#!/bin/bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

target="README.md"
tmp=$(mktemp)
trap 'rm -f $tmp' EXIT

sed -n '/^-/q;p' "$target" >>"$tmp"
for formula in Formula/*.rb; do
  name=$(basename "$formula" .rb)
  homepage=$(sed -n -E "/homepage/{s/.*'(.*)'.*/\\1/p;q;}" "$formula")
  version=$(sed -n -E "/version/{s/.*'(.*)'.*/\\1/p;q;}" "$formula")
  echo "- [$name]($homepage) $version" >>"$tmp"
done
sed -n '1,/^-/d;/^$/,$p' "$target" >>"$tmp"

mv "$tmp" "$target"
