#!/bin/bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

target="README.md"
tmp=$(mktemp -t "update-readme.XXXXXXXX")
outtmp=$(mktemp -t "update-readme.XXXXXXXX")
trap 'rm -rf $tmp $outtmp' EXIT SIGHUP SIGINT SIGQUIT SIGTERM

for formula in $(git ls-files Formula | grep "[.]rb$"); do
  homepage=$(sed -n "/homepage/s/^.*'\\(.*\\)'.*/\\1/gp" "$formula" | head -n1)
  name=$(basename "${formula%.*}")
  version=$(sed -n "/version/s/^.*'\\(.*\\)'.*/\\1/gp" "$formula" | head -n1)
  echo "- [$name]($homepage) $version"
done > "$tmp"

state=0
while IFS= read -r line; do
  if [[  $state -le 1 && $line == '-'* ]]; then
    state=1
    continue
  elif [[ $state == 1 ]]; then
    state=2
    cat "$tmp"
  fi
  echo "$line"
done < "$target" > "$outtmp"

mv "$outtmp" "$target"
