#!/bin/bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

tmp=$(mktemp -t "update.XXXXXXXX")
trap 'rm -rf $tmp' EXIT SIGHUP SIGINT SIGQUIT SIGTERM

if [[ $# == 0 ]]; then
  formulas=$(git ls-files Formula | grep "[.]rb$")
else
  formulas=$*
fi

for formula in $formulas; do
  formulate update "$formula" 2> >(tee "$tmp" >&2)
  if grep "Updated" "$tmp" > /dev/null; then
    name=$(basename "${formula%.*}")
    version=$(sed -n "/version/s/^.*'\\(.*\\)'.*/\\1/gp" "$formula" | head -n1)
    ./script/update-readme
    git commit -a -m "$name v$version"
  fi
done
