#!/bin/bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

tmp=$(mktemp)
trap 'rm -f $tmp' EXIT

if [[ $# -eq 0 ]]; then
  formulas=(Formula/*.rb)
else
  formulas=("$@")
fi

for formula in "${formulas[@]}"; do
  formulate update "$formula" 2> >(tee "$tmp" >&2)
  if grep -q "Updated" "$tmp"; then
    script/update-readme
    name=$(basename "$formula" .rb)
    version=$(sed -n -E "/version/{s/.*'(.*)'.*/\\1/p;q;}" "$formula")
    git commit -a -m "$name v$version"
  fi
done
